version: "3.8"
services:
  backend:
    image: "eokonkwo/springboot-react-fullstack:16.1.2022.2.24.44"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev