version: "3.8"
services:
  backend:
    image: "eokonkwo/springboot-react-fullstack:19.1.2022.8.27.50"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev