version: "3.8"
services:
  backend:
    image: "eokonkwo/springboot-react-fullstack:19.1.2022.10.55.38"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev